### ISSUE TITLE
Странные PoS-теги

### ISSUE THREAD

**Issue by Shtepser** [UniversalDependencies/UD_Russian-Taiga#2]
Добрый день!

Использовал Ваш парсер со `Stanza`, заметил следующее:

В предложении
_Маловероятно, что уничтожит планету._
«маловероятно» было отмечено как прилагательное (`ADJ`), хотя оно является наречием.
В чём может быть причина этого?

С уважением, Анатолий Полетаев

**Comment by olesar** [comment]
Добрый день, Анатолий, спасибо за комментарий!

ошибки в разметке нет. UD здесь следует морфологическому стандарту НКРЯ, в котором "маловероятно, что <подчиненная клауза>" считается кратким прилагательным:
https://processing.ruscorpora.ru/search.xml?lang=ru&sort=i_grtagging&req=%D0%BC%D0%B0%D0%BB%D0%BE%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%2C%20%D1%87%D1%82%D0%BE&startyear=1800&mydocsize=&mysize=&spp=&mysentsize=&dpp=&mycorp=&mysent=&api=1.0&text=lexform&mode=main&env=alpha&nodia=1&endyear=2019&spd=&p=1

У маловероятно сохраняется способность присоединять субъект, что для наречия недопустимо:
Это маловероятно, что ....
https://processing.ruscorpora.ru/search.xml?mode=paper&p=0&nodia=1&lang=ru&sort=i_grtagging&startyear=1800&dpp=&spp=&text=lexform&req=%D1%8D%D1%82%D0%BE+%2A+%D0%BC%D0%B0%D0%BB%D0%BE%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%2C+%D1%87%D1%82%D0%BE&api=1.0&env=alpha&spd=&endyear=2019
